import img from '../images/movieImg.png';

export const moviesData = [
    {
      title: "33 слова о дизайне",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 1"),
    },
    {
      title: "Movie Title 2",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 2"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
    {
      title: "Movie Title 3",
      duration: "1ч 17м",
      imageUrl: img,
      isLiked: true,
      onLikeClick: () => console.log("Like button clicked for Movie Title 3"),
    },
  ];